// src/app/components/batches/inventory-pricing-section.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface QuantityDiscount {
  units: string;
  pricePerUnit: string;
}

@Component({
  selector: 'app-inventory-pricing-section',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="space-y-6">
      <div class="rounded-lg border border-border/50 bg-card">
        <div class="border-b border-border/30 px-4 pb-3 pt-4">
          <div class="flex items-center gap-2 text-base font-semibold">
            <svg viewBox="0 0 24 24" class="h-4 w-4 text-primary" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
            </svg>
            Inventory
          </div>
        </div>
        <div class="space-y-4 px-4 pb-4 pt-3">
          <div class="flex items-center gap-4">
            <div class="flex w-40 items-center gap-2 text-sm text-muted-foreground">
              Stock
              <span class="text-muted-foreground" data-tooltip="Available quantity for sale">?</span>
            </div>
            <input
              type="number"
              min="0"
              class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
              [class.border-destructive]="errors['quantity']"
              [ngModel]="value('quantity')"
              (ngModelChange)="update('quantity', $event)"
              placeholder="0"
            />
          </div>
          <div class="flex items-center gap-4">
            <div class="flex w-40 items-center gap-2 text-sm text-muted-foreground">
              Shipping ($)
              <span class="text-muted-foreground" data-tooltip="Shipping cost for this product">?</span>
            </div>
            <input
              type="number"
              step="0.01"
              min="0"
              class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
              [class.border-destructive]="errors['shipping_cost']"
              [ngModel]="value('shipping_cost')"
              (ngModelChange)="update('shipping_cost', $event)"
              placeholder="0.00"
            />
          </div>
          <div class="flex items-center gap-4">
            <div class="flex w-40 items-center gap-2 text-sm text-muted-foreground">
              Condition
              <span class="text-muted-foreground" data-tooltip="Product condition for compliance">?</span>
            </div>
            <select
              class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
              [class.border-destructive]="errors['condition']"
              [ngModel]="value('condition') || 'new'"
              (ngModelChange)="update('condition', $event)"
            >
              <option value="new">New</option>
              <option value="used_like_new">Used - Like New</option>
              <option value="used_very_good">Used - Very Good</option>
              <option value="used_good">Used - Good</option>
              <option value="used_acceptable">Used - Acceptable</option>
              <option value="refurbished">Refurbished</option>
              <option value="renewed">Renewed</option>
            </select>
          </div>
        </div>
      </div>

      <details class="rounded-lg border border-border/50 bg-card" [open]="standardOpen">
        <summary class="flex cursor-pointer items-center gap-2 px-4 py-3 text-base font-semibold" (click)="standardOpen = !standardOpen">
          <svg viewBox="0 0 24 24" class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M6 9l6 6 6-6" />
          </svg>
          Standard price
        </summary>
        <div class="space-y-4 px-4 pb-4">
          <div class="space-y-3">
            <div class="flex items-center gap-4">
              <div class="w-40 text-sm text-muted-foreground">Price ($)</div>
              <input
                type="number"
                step="0.01"
                min="0"
                class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
                [class.border-destructive]="errors['price']"
                [ngModel]="value('price')"
                (ngModelChange)="update('price', $event)"
                placeholder="0.00"
              />
            </div>
            <div class="flex items-center gap-4">
              <div class="w-40 text-sm text-muted-foreground">MSRP ($)</div>
              <input
                type="number"
                step="0.01"
                min="0"
                class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
                [class.border-destructive]="errors['msrp']"
                [ngModel]="value('msrp')"
                (ngModelChange)="update('msrp', $event)"
                placeholder="0.00"
              />
            </div>
            <div class="flex items-center gap-4">
              <div class="w-40 text-sm text-muted-foreground">Minimum price ($)</div>
              <input
                type="number"
                step="0.01"
                min="0"
                class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
                [ngModel]="value('min_price')"
                (ngModelChange)="update('min_price', $event)"
                placeholder="0.00"
              />
            </div>
            <div class="flex items-center gap-4">
              <div class="w-40 text-sm text-muted-foreground">Maximum price ($)</div>
              <input
                type="number"
                step="0.01"
                min="0"
                class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
                [ngModel]="value('max_price')"
                (ngModelChange)="update('max_price', $event)"
                placeholder="0.00"
              />
            </div>
          </div>

          <button type="button" class="text-sm font-medium text-primary hover:underline">Pricing health</button>

          <div class="border-t border-border/40 pt-4">
            <div class="mb-3 flex items-center justify-between">
              <h4 class="text-sm font-semibold">Reference prices</h4>
              <button type="button" class="text-sm text-primary hover:underline">Learn more</button>
            </div>
            <div class="space-y-2 text-sm">
              <div class="flex items-center justify-between py-1">
                <span class="text-muted-foreground">Featured offer</span>
                <span class="text-muted-foreground">{{ value('featured_offer_price') || '-' }}</span>
              </div>
              <div class="flex items-center justify-between py-1">
                <span class="text-muted-foreground">Lowest price</span>
                <span class="text-muted-foreground">{{ value('lowest_price') || '-' }}</span>
              </div>
              <div class="flex items-center justify-between py-1">
                <span class="text-muted-foreground">Competitive price</span>
                <span class="text-muted-foreground">{{ value('competitive_price') || '-' }}</span>
              </div>
              <div class="flex items-center justify-between py-1">
                <span class="text-muted-foreground">Minimum price</span>
                <span class="text-muted-foreground">{{ value('min_similar_price') || '-' }}</span>
              </div>
              <div class="flex items-center justify-between py-1">
                <span class="text-muted-foreground">Median price</span>
                <span class="text-muted-foreground">{{ value('median_similar_price') || '-' }}</span>
              </div>
            </div>
          </div>
        </div>
      </details>

      <details class="rounded-lg border border-border/50 bg-card" [open]="businessOpen">
        <summary class="flex cursor-pointer items-center gap-2 px-4 py-3 text-base font-semibold" (click)="businessOpen = !businessOpen">
          <svg viewBox="0 0 24 24" class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M6 9l6 6 6-6" />
          </svg>
          Business price
        </summary>
        <div class="space-y-4 px-4 pb-4">
          <div class="flex items-center gap-4">
            <div class="w-40 text-sm text-muted-foreground">Business price ($)</div>
            <input
              type="number"
              step="0.01"
              min="0"
              class="h-9 w-48 rounded-md border border-border bg-background px-3 text-sm"
              [ngModel]="value('business_price')"
              (ngModelChange)="update('business_price', $event)"
              placeholder="0.00"
            />
          </div>

          <div class="space-y-3">
            <div class="text-sm font-medium">Quantity discounts</div>
            <div class="flex items-center gap-1 rounded-full bg-muted px-2 py-1 text-sm">
              <button
                type="button"
                class="rounded-full px-3 py-1"
                [ngClass]="discountType === 'percent' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'"
                (click)="discountType = 'percent'"
              >
                % off
              </button>
              <span class="text-muted-foreground">|</span>
              <button
                type="button"
                class="rounded-full px-3 py-1"
                [ngClass]="discountType === 'fixed' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'"
                (click)="discountType = 'fixed'"
              >
                Fixed price
              </button>
            </div>

            <div *ngIf="discounts.length > 0" class="space-y-2">
              <div class="grid grid-cols-[1fr_1fr_auto] gap-2 text-sm font-medium text-muted-foreground">
                <span>Units</span>
                <span>{{ discountType === 'percent' ? '% off' : 'Price per unit ($)' }}</span>
                <span class="w-8"></span>
              </div>
              <div *ngFor="let discount of discounts; let i = index" class="grid grid-cols-[1fr_1fr_auto] items-center gap-2">
                <input
                  type="number"
                  min="1"
                  class="h-9 rounded-md border border-border bg-background px-3 text-sm"
                  [ngModel]="discount.units"
                  (ngModelChange)="updateDiscount(i, 'units', $event)"
                  placeholder="0"
                />
                <input
                  type="number"
                  step="0.01"
                  min="0"
                  class="h-9 rounded-md border border-border bg-background px-3 text-sm"
                  [ngModel]="discount.pricePerUnit"
                  (ngModelChange)="updateDiscount(i, 'pricePerUnit', $event)"
                  placeholder="0.00"
                />
                <button type="button" class="h-9 w-9 rounded-md text-primary hover:text-destructive" (click)="removeDiscount(i)">
                  x
                </button>
              </div>
            </div>

            <button
              type="button"
              class="inline-flex items-center gap-2 rounded-md border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/10"
              (click)="addDiscount()"
            >
              + Add discount
            </button>
          </div>
        </div>
      </details>
    </div>
  `,
})
export class InventoryPricingSectionComponent {
  @Input() values: Record<string, string> = {};
  @Input() errors: Record<string, boolean> = {};
  @Output() valueChange = new EventEmitter<{ key: string; value: string }>();

  standardOpen = true;
  businessOpen = false;
  discountType: 'percent' | 'fixed' = 'fixed';

  get discounts(): QuantityDiscount[] {
    try {
      const stored = this.values['quantity_discounts'];
      return stored ? (JSON.parse(stored) as QuantityDiscount[]) : [];
    } catch {
      return [];
    }
  }

  value(key: string): string {
    return this.values[key] || '';
  }

  update(key: string, value: string): void {
    this.valueChange.emit({ key, value });
  }

  addDiscount(): void {
    const next = [...this.discounts, { units: '', pricePerUnit: '' }];
    this.valueChange.emit({ key: 'quantity_discounts', value: JSON.stringify(next) });
  }

  removeDiscount(index: number): void {
    const next = this.discounts.filter((_, i) => i !== index);
    this.valueChange.emit({ key: 'quantity_discounts', value: JSON.stringify(next) });
  }

  updateDiscount(index: number, field: keyof QuantityDiscount, value: string): void {
    const next = [...this.discounts];
    next[index] = { ...next[index], [field]: value };
    this.valueChange.emit({ key: 'quantity_discounts', value: JSON.stringify(next) });
  }
}

// src/components/batches/InventoryPricingSection.tsx
import { useState } from 'react';
import { ChevronDown, ChevronRight, CheckCircle2, Plus, Trash2, Package } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { HelpCircle } from 'lucide-react';
import { cn } from '@/lib/utils';

const CONDITION_OPTIONS = [
  { value: 'new', label: 'New' },
  { value: 'used_like_new', label: 'Used - Like New' },
  { value: 'used_very_good', label: 'Used - Very Good' },
  { value: 'used_good', label: 'Used - Good' },
  { value: 'used_acceptable', label: 'Used - Acceptable' },
  { value: 'refurbished', label: 'Refurbished' },
  { value: 'renewed', label: 'Renewed' },
];

interface QuantityDiscount {
  units: string;
  pricePerUnit: string;
}

interface InventoryPricingSectionProps {
  values: Record<string, string>;
  onChange: (key: string, value: string) => void;
  errors?: Record<string, boolean>;
}

export function InventoryPricingSection({ values, onChange, errors = {} }: InventoryPricingSectionProps) {
  const [standardOpen, setStandardOpen] = useState(true);
  const [businessOpen, setBusinessOpen] = useState(false);
  const [discountType, setDiscountType] = useState<'percent' | 'fixed'>('fixed');
  
  // Parse quantity discounts from stored JSON
  const parseDiscounts = (): QuantityDiscount[] => {
    try {
      const stored = values['quantity_discounts'];
      if (stored) {
        return JSON.parse(stored);
      }
    } catch (e) {
      console.error('Error parsing quantity discounts:', e);
    }
    return [];
  };
  
  const discounts = parseDiscounts();
  
  const updateDiscounts = (newDiscounts: QuantityDiscount[]) => {
    onChange('quantity_discounts', JSON.stringify(newDiscounts));
  };
  
  const addDiscount = () => {
    updateDiscounts([...discounts, { units: '', pricePerUnit: '' }]);
  };
  
  const removeDiscount = (index: number) => {
    updateDiscounts(discounts.filter((_, i) => i !== index));
  };
  
  const updateDiscount = (index: number, field: keyof QuantityDiscount, value: string) => {
    const newDiscounts = [...discounts];
    newDiscounts[index] = { ...newDiscounts[index], [field]: value };
    updateDiscounts(newDiscounts);
  };

  // Reference prices (would come from marketplace API in real implementation)
  const referenceData = {
    featuredOffer: values['featured_offer_price'] || null,
    lowestPrice: values['lowest_price'] || null,
    competitivePrice: values['competitive_price'] || null,
    minSimilar: values['min_similar_price'] || null,
    medianSimilar: values['median_similar_price'] || null,
  };

  // Get inventory values
  const stock = parseInt(values['quantity'] || values['available_stock'] || '0') || 0;
  const shippingCost = values['shipping_cost'] || '';

  return (
    <div className="space-y-6">
      {/* Inventory Section */}
      <Card className="border-border/50">
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Package className="w-4 h-4 text-primary" />
            Inventory
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0 space-y-4">
          {/* Stock */}
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 w-40 shrink-0">
              <Label className="text-sm text-muted-foreground">
                Stock
              </Label>
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="w-3.5 h-3.5 text-muted-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="top" className="max-w-xs bg-popover border z-50">
                    <p className="text-xs">Available quantity for sale</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
            <Input
              type="number"
              min="0"
              value={values['quantity'] || values['available_stock'] || ''}
              onChange={(e) => onChange('quantity', e.target.value)}
              className={cn(
                "max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
                errors['quantity'] && "border-destructive"
              )}
              placeholder="0"
            />
          </div>

          {/* Shipping Cost */}
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 w-40 shrink-0">
              <Label className="text-sm text-muted-foreground">
                Shipping ($)
              </Label>
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="w-3.5 h-3.5 text-muted-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="top" className="max-w-xs bg-popover border z-50">
                    <p className="text-xs">Shipping cost for this product</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
            <Input
              type="number"
              step="0.01"
              min="0"
              value={values['shipping_cost'] || ''}
              onChange={(e) => onChange('shipping_cost', e.target.value)}
              className={cn(
                "max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
                errors['shipping_cost'] && "border-destructive"
              )}
              placeholder="0.00"
            />
          </div>

          {/* Condition */}
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 w-40 shrink-0">
              <Label className="text-sm text-muted-foreground">
                Condition
              </Label>
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="w-3.5 h-3.5 text-muted-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="top" className="max-w-xs bg-popover border z-50">
                    <p className="text-xs">Product condition for marketplace compliance</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
            <Select
              value={values['condition'] || 'new'}
              onValueChange={(value) => onChange('condition', value)}
            >
              <SelectTrigger className={cn(
                "max-w-48",
                errors['condition'] && "border-destructive"
              )}>
                <SelectValue placeholder="Select condition" />
              </SelectTrigger>
              <SelectContent className="bg-popover border z-50">
                {CONDITION_OPTIONS.map((option) => (
                  <SelectItem key={option.value} value={option.value}>
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Standard Price Section */}
      <Collapsible open={standardOpen} onOpenChange={setStandardOpen}>
        <CollapsibleTrigger asChild>
          <button className="flex items-center gap-2 w-full text-left py-2 font-semibold text-base hover:text-primary transition-colors">
            {standardOpen ? (
              <ChevronDown className="w-5 h-5" />
            ) : (
              <ChevronRight className="w-5 h-5" />
            )}
            Standard price
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent className="space-y-4 pt-2">
          {/* Price Fields */}
          <div className="space-y-3">
            <div className="flex items-center gap-4">
              <Label className="w-40 text-sm text-muted-foreground shrink-0">
                Price ($)
              </Label>
              <Input
                type="number"
                step="0.01"
                min="0"
                value={values['price'] || ''}
                onChange={(e) => onChange('price', e.target.value)}
                className={cn(
                  "max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
                  errors['price'] && "border-destructive"
                )}
                placeholder="0.00"
              />
            </div>

            <div className="flex items-center gap-4">
              <Label className="w-40 text-sm text-muted-foreground shrink-0">
                MSRP ($)
              </Label>
              <Input
                type="number"
                step="0.01"
                min="0"
                value={values['msrp'] || ''}
                onChange={(e) => onChange('msrp', e.target.value)}
                className={cn(
                  "max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none",
                  errors['msrp'] && "border-destructive"
                )}
                placeholder="0.00"
              />
            </div>
            
            <div className="flex items-center gap-4">
              <Label className="w-40 text-sm text-muted-foreground shrink-0">
                Minimum price ($)
              </Label>
              <Input
                type="number"
                step="0.01"
                min="0"
                value={values['min_price'] || ''}
                onChange={(e) => onChange('min_price', e.target.value)}
                className="max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                placeholder="0.00"
              />
            </div>
            
            <div className="flex items-center gap-4">
              <Label className="w-40 text-sm text-muted-foreground shrink-0">
                Maximum price ($)
              </Label>
              <Input
                type="number"
                step="0.01"
                min="0"
                value={values['max_price'] || ''}
                onChange={(e) => onChange('max_price', e.target.value)}
                className="max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                placeholder="0.00"
              />
            </div>
          </div>
          
          {/* Pricing Health Link */}
          <button className="text-sm text-primary hover:underline font-medium">
            Pricing health
          </button>
          
          {/* Reference Prices Section */}
          <div className="border-t pt-4 mt-4">
            <div className="flex items-center justify-between mb-3">
              <h4 className="font-semibold text-sm">Reference prices</h4>
              <button className="text-sm text-primary hover:underline">
                Learn more
              </button>
            </div>
            
            <div className="space-y-2 text-sm">
              <div className="flex items-center justify-between py-1">
                <span className="text-muted-foreground">Featured offer</span>
                {referenceData.featuredOffer ? (
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                    ${referenceData.featuredOffer} + $0.00
                  </span>
                ) : (
                  <span className="text-muted-foreground">-</span>
                )}
              </div>
              
              <div className="flex items-center justify-between py-1">
                <span className="text-muted-foreground">Lowest price</span>
                {referenceData.lowestPrice ? (
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                    ${referenceData.lowestPrice} + $0.00
                  </span>
                ) : (
                  <span className="text-muted-foreground">-</span>
                )}
              </div>
              
              <div className="flex items-center justify-between py-1">
                <span className="text-muted-foreground">Competitive price</span>
                <span className="text-muted-foreground">
                  {referenceData.competitivePrice ? `$${referenceData.competitivePrice}` : '-'}
                </span>
              </div>
              
              <div className="flex items-center justify-between py-1">
                <div>
                  <span className="text-muted-foreground">Minimum price</span>
                  <p className="text-xs text-muted-foreground/70">Similar product</p>
                </div>
                <span className="text-muted-foreground">
                  {referenceData.minSimilar ? `$${referenceData.minSimilar}` : '-'}
                </span>
              </div>
              
              <div className="flex items-center justify-between py-1">
                <div>
                  <span className="text-muted-foreground">Median price</span>
                  <p className="text-xs text-muted-foreground/70">Similar product</p>
                </div>
                <span className="text-muted-foreground">
                  {referenceData.medianSimilar ? `$${referenceData.medianSimilar}` : '-'}
                </span>
              </div>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
      
      {/* Business Price Section */}
      <Collapsible open={businessOpen} onOpenChange={setBusinessOpen}>
        <CollapsibleTrigger asChild>
          <button className="flex items-center gap-2 w-full text-left py-2 font-semibold text-base hover:text-primary transition-colors border-t pt-4">
            {businessOpen ? (
              <ChevronDown className="w-5 h-5" />
            ) : (
              <ChevronRight className="w-5 h-5" />
            )}
            Business price
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent className="space-y-4 pt-2">
          {/* Business Price Field */}
          <div className="flex items-center gap-4">
            <Label className="w-40 text-sm text-muted-foreground shrink-0">
              Business price ($)
            </Label>
            <Input
              type="number"
              step="0.01"
              min="0"
              value={values['business_price'] || ''}
              onChange={(e) => onChange('business_price', e.target.value)}
              className="max-w-48 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
              placeholder="0.00"
            />
          </div>
          
          {/* Quantity Discounts */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">Quantity discounts</Label>
            
            {/* Discount Type Toggle */}
            <div className="flex items-center gap-1 bg-muted rounded-full p-1 w-fit">
              <button
                type="button"
                onClick={() => setDiscountType('percent')}
                className={cn(
                  "px-4 py-1.5 rounded-full text-sm font-medium transition-all",
                  discountType === 'percent'
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                % off
              </button>
              <span className="text-muted-foreground">|</span>
              <button
                type="button"
                onClick={() => setDiscountType('fixed')}
                className={cn(
                  "px-4 py-1.5 rounded-full text-sm font-medium transition-all",
                  discountType === 'fixed'
                    ? "bg-primary text-primary-foreground"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                Fixed price
              </button>
            </div>
            
            {/* Discounts Table */}
            {discounts.length > 0 && (
              <div className="space-y-2">
                <div className="grid grid-cols-[1fr_1fr_auto] gap-2 text-sm font-medium text-muted-foreground">
                  <span>Units</span>
                  <span>{discountType === 'percent' ? '% off' : 'Price per unit ($)'}</span>
                  <span className="w-8" />
                </div>
                
                {discounts.map((discount, idx) => (
                  <div key={idx} className="grid grid-cols-[1fr_1fr_auto] gap-2 items-center">
                    <Input
                      type="number"
                      min="1"
                      value={discount.units}
                      onChange={(e) => updateDiscount(idx, 'units', e.target.value)}
                      className="[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                      placeholder="0"
                    />
                    <Input
                      type="number"
                      step="0.01"
                      min="0"
                      value={discount.pricePerUnit}
                      onChange={(e) => updateDiscount(idx, 'pricePerUnit', e.target.value)}
                      className="[appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                      placeholder="0.00"
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      onClick={() => removeDiscount(idx)}
                      className="h-9 w-9 text-primary hover:text-destructive"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                ))}
              </div>
            )}
            
            {/* Add Discount Button */}
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={addDiscount}
              className="gap-1.5 text-primary border-primary hover:bg-primary/10"
            >
              <Plus className="w-4 h-4" />
              Add discount
            </Button>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </div>
  );
}
